from app.services.pdf_inspector import inspect_pdf
from app.services.page_renderer import render_pages
from app.services.preprocessor import preprocess_scanned_pages

from app.services.ocr_service import process_ocr

from app.services.classification_service import classify_pages

from app.models.page import Page
from app.services.grouping_service import group_pages



def analyze_job(
    db,
    job,
    pdf_path
):


    # ==================================================
    # LAYER 1
    # PDF ANALYSIS
    # Native vs Scanned detection
    # ==================================================

    analysis = inspect_pdf(
        pdf_path
    )



    # ==================================================
    # Render PDF pages
    # PDF page -> PNG
    #
    # Necessary for:
    # - scanned preprocessing
    # - OCR
    # ==================================================

    images = render_pages(
        pdf_path,
        job.job_id
    )



    # ==================================================
    # LAYER 2
    # Image preprocessing
    #
    # Only scanned pages are modified
    # Native pages keep original text layer
    # ==================================================

    images = preprocess_scanned_pages(
        analysis,
        images
    )



    # ==================================================
    # Create Page database objects
    # ==================================================

    pages = []


    for data, image in zip(
        analysis,
        images
    ):


        page = Page(

            job_id=job.job_id,

            image_path=image,

            **data

        )


        db.add(page)

        pages.append(page)



    db.commit()



    # ==================================================
    # OCR QUICK PASS
    #
    # Only:
    # source_type = SCANNED
    #
    # Native:
    # raw_text already exists from PyMuPDF
    #
    # Scanned:
    # raw_text generated by Tesseract
    # ==================================================

    pages = process_ocr(
        db,
        pages
    )



    # ==================================================
    # LAYER 3
    # PAGE CLASSIFICATION
    #
    # Input:
    # Native  -> raw_text Layer 1
    # Scanned -> OCR text Layer 2
    #
    # Output:
    # document_type
    # confidence
    # classification_source
    # ==================================================

    pages = classify_pages(
        db,
        pages
    )
    groups = group_pages(
    db,
    job.job_id,
    pages
)



    # ==================================================
    # Update job status
    # ==================================================

    job.status = "ANALYZED"


    db.commit()



    return pages