"""add page classification fields

Revision ID: beeabc599827
Revises: 24ae497b9f88
Create Date: 2026-07-10 10:22:20.778853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beeabc599827'
down_revision: Union[str, Sequence[str], None] = '24ae497b9f88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('document_type', sa.String(), nullable=True))
    op.add_column('pages', sa.Column('classification_confidence', sa.Float(), nullable=True))
    op.add_column('pages', sa.Column('classification_source', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'classification_source')
    op.drop_column('pages', 'classification_confidence')
    op.drop_column('pages', 'document_type')
    # ### end Alembic commands ###
